#!/bin/bash

if [[ $# == 3 ]]
then
    corefile0=$1
    corefile1=$2
    outfile=$3
    shift 3
else
  if [[ $# == 2 ]]
  then
    corefile0=$1
    outfile=$2
    shift 2
  else
    echo Usage: $0 core0 [core1] out >&2
    exit 1
  fi
fi


tmp=/tmp/singlebin-$$
if [[ ! -f version.txt ]]
then
	echo no version.txt file
	exit 1
fi

version=`cat version.txt`
echo header version $version

echo -n RPRC > $outfile
./wrints $version 1012 >> $outfile

if [[ -f $corefile0 ]]
then
	md5sum $corefile0 >> $outfile
	stat -c "%s %z" $corefile0 >> $outfile
	nm $corefile0 | grep SysMin_Module_State_0_outbuf__A | cut -d ' ' -f 1 >> $outfile
fi

if [[ -f $corefile1 ]]
then
	md5sum $corefile1 >> $outfile
	stat -c "%s %z" $corefile1 >> $outfile
	nm $corefile1 | grep SysMin_Module_State_0_outbuf__A | cut -d ' ' -f 1 >> $outfile
fi

(( numbytesneeded = 1024 - $(stat -c "%s" $outfile) ))
dd if=/dev/zero of=$tmp bs=$numbytesneeded count=1 > /dev/null 2>&1
cat $tmp >> $outfile
rm $tmp
